gun1=int(input("1. gün okuduğu sayfa sayısını yazın"))
gun2=int(input("2. gün okuduğu sayfa sayısını yazın"))
gun3=int(input("3. gün okuduğu sayfa sayısını yazın"))
gun4=int(input("4. gün okuduğu sayfa sayısını yazın"))
gun5=int(input("5. gün okuduğu sayfa sayısını yazın"))
gun6=int(input("6. gün okuduğu sayfa sayısını yazın"))
gun7=int(input("7. gün okuduğu sayfa sayısını yazın"))
toplam=(gün1+gün2+gün3+gün4+gün5+gün6+gün7)
print("7 günün okuduğu kitap sayısının toplamı",toplam)